spring:
  datasource:
    url: "jdbc:postgresql://localhost:5432/kiosk_db"
    password: 3884
    username: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

#      update-> change bosa update, create , validate -> liquibase migartion